### ISSUE TITLE
Running fbv in background

### ISSUE THREAD

**Issue by avanc** [godspeed1989/fbv#18]
I want to use fbv as slide show in background. While playing around, I discovered some unexpected problems:

* fbv is not stopable by Ctrl-C
   * But it can be stopped using `kill -INT <PID>`

* fbv cannot be started in background (`fbv image.jpg &`)
    * It exists with SIGTTOU
    * How can fbv be started non-interactively?

**Comment by godspeed1989** [comment]
Fixed in https://github.com/godspeed1989/fbv/pull/19
